### ISSUE TITLE
Information - blocked by linewize

### ISSUE THREAD

**Issue by jake-378** [BOBLO123/silly-40-buttons#5]
Does not work with linewize. Website ends up loading and then gets sent to linewize blocked page like normal.

**Comment by Raf128** [comment]
This can happen sometimes with certain websites, but since this happens on every website I will put Linewize in not working.

**Comment by Raf128** [comment]
Can you try the newest version of Hipposite on the testing branch? Try using the slider and see if the max setting works or not.
